//اضافه کردن خود آهنگ یادت رفته حتما اضاف بکن
import image from './assets/images/Image 59.png'
let MusicData =[
    {
        "Id":'1',
        "Name":'HEF',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },
    {
        "Id":'2',
        "Name":'fdasfds',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    }, 
    {
        "Id":'3',
        "Name":'fadsf',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },
       {
        "Id":'4',
        "Name":'a',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },
    {
        "Id":'5',
        "Name":'d',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },
       {
        "Id":'6',
        "Name":'f',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },
    {
        "Id":'7',
        "Name":'g',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },
       {
        "Id":'8',
        "Name":'j',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },   {
        "Id":'9',
        "Name":'k',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },
    {
        "Id":'10',
        "Name":'HEF',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },   {
        "Id":'11',
        "Name":'HEF',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },   {
        "Id":'12',
        "Name":'HEF',
        "Artist":'Koud',
        'Image':{image},
        "AddToLibrary":'false',
        'Play':'false',
        'Repeat':'false'
    },
    
]
export {MusicData}